[package]
name = "crystalvm"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4.0"
fltk = { version = "1.4.5", features = ["rwh05", "no-images", "no-pango"] }
pixels = "0.13.0"

[build-dependencies]
image = "0.24.6"
